language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8
        - CXXSTD=c++11

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8
        - CXXSTD=c++1y

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER=g++-4.9
        - CXXSTD=c++11

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER=g++-4.9
        - CXXSTD=c++14

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=g++-5
        - CXXSTD=c++11

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=g++-5
        - CXXSTD=c++14

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER=g++-5
        - CXXSTD=c++1z

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6
        - CXXSTD=c++11

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6
        - CXXSTD=c++14

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6
        - CXXSTD=c++17

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7
        - CXXSTD=c++11

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7
        - CXXSTD=c++14

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7
        - CXXSTD=c++17

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=clang++
        - CXXSTD=c++11

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=clang++
        - CXXSTD=c++1y

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env:
        - COMPILER=clang++-3.5
        - CXXSTD=c++11

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env:
        - COMPILER=clang++-3.6
        - CXXSTD=c++11

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env:
        - COMPILER=clang++-3.6
        - CXXSTD=c++14

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - COMPILER=clang++-3.7
        - CXXSTD=c++11

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - COMPILER=clang++-3.7
        - CXXSTD=c++14

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - COMPILER=clang++-3.7
        - CXXSTD=c++1z

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env:
        - COMPILER=clang++-3.8
        - CXXSTD=c++11

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env:
        - COMPILER=clang++-3.8
        - CXXSTD=c++14

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env:
        - COMPILER=clang++-3.8
        - CXXSTD=c++1z

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9']
      env:
        - COMPILER=clang++-3.9
        - CXXSTD=c++11

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9', 'g++-4.9']
      env:
        - COMPILER=clang++-3.9
        - CXXSTD=c++14

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9', 'g++-4.9']
      env:
        - COMPILER=clang++-3.9
        - CXXSTD=c++1z

# Clang 4.0 has a bug which prevents it from compiling our code :(

#    - os: linux
#      dist: trusty
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
#          packages: ['clang-4.0', 'g++-4.9']
#      env:
#        - COMPILER=clang++-4.0
#        - CXXSTD=c++11

#    - os: linux
#      dist: trusty
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
#          packages: ['clang-4.0', 'g++-4.9']
#      env:
#        - COMPILER=clang++-4.0
#        - CXXSTD=c++14

#    - os: linux
#      dist: trusty
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
#          packages: ['clang-4.0', 'g++-4.9']
#      env:
#        - COMPILER=clang++-4.0
#        - CXXSTD=c++1z

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - COMPILER=clang++
        - CXXSTD=c++11

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - COMPILER=clang++
        - CXXSTD=c++14

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - COMPILER=clang++
        - CXXSTD=c++1z

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - COMPILER=clang++
        - CXXSTD=c++11

# Compiler bug?

#    - os: osx
#      osx_image: xcode7.3
#      compiler: clang
#      env:
#        - COMPILER=clang++
#        - CXXSTD=c++14

#    - os: osx
#      osx_image: xcode7.3
#      compiler: clang
#      env:
#        - COMPILER=clang++
#        - CXXSTD=c++1z

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - COMPILER=clang++
        - CXXSTD=c++11

# Compiler bug?

#    - os: osx
#      osx_image: xcode8.3
#      compiler: clang
#      env:
#        - COMPILER=clang++
#        - CXXSTD=c++14

#    - os: osx
#      osx_image: xcode8.3
#      compiler: clang
#      env:
#        - COMPILER=clang++
#        - CXXSTD=c++1z

script:
  make CXX=$COMPILER -j3
