language: generic
os: linux
dist: trusty

matrix:
  include:
    - compiler: gcc
      env:
        - CXX=g++-4.8
        - CXXSTD=-std=c++11

    - compiler: gcc
      env:
        - CXX=g++-4.8
        - CXXSTD=-std=c++1y

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - CXX=g++-4.9
        - CXXSTD=-std=c++11

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - CXX=g++-4.9
        - CXXSTD=-std=c++14

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - CXX=g++-5
        - CXXSTD=-std=c++11

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - CXX=g++-5
        - CXXSTD=-std=c++14

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - CXX=g++-5
        - CXXSTD=-std=c++1z

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - CXX=g++-6
        - CXXSTD=-std=c++11

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - CXX=g++-6
        - CXXSTD=-std=c++14

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - CXX=g++-6
        - CXXSTD=-std=c++17

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CXXSTD=-std=c++11

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CXXSTD=-std=c++14

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CXXSTD=-std=c++17

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - CXX=g++-8
        - CXXSTD=-std=c++11

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - CXX=g++-8
        - CXXSTD=-std=c++14

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - CXX=g++-8
        - CXXSTD=-std=c++17

    - dist: precise
      compiler: clang
      env:
        - CXX=clang++
        - CXXSTD=-std=c++11

    - dist: precise
      compiler: clang
      env:
        - CXX=clang++
        - CXXSTD=-std=c++1y

    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.5']
      env:
        - CXX=clang++-3.5
        - CXXSTD=-std=c++11

    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.6']
      env:
        - CXX=clang++-3.6
        - CXXSTD=-std=c++11

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-3.6', 'g++-4.9']
      env:
        - CXX=clang++-3.6
        - CXXSTD=-std=c++14

    - dist: precise
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - CXX=clang++-3.7
        - CXXSTD=-std=c++11

    - dist: precise
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - CXX=clang++-3.7
        - CXXSTD=-std=c++14

    - dist: precise
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - CXX=clang++-3.7
        - CXXSTD=-std=c++1z

    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.8']
      env:
        - CXX=clang++-3.8
        - CXXSTD=-std=c++11

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-3.8', 'g++-4.9']
      env:
        - CXX=clang++-3.8
        - CXXSTD=-std=c++14

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-3.8', 'g++-4.9']
      env:
        - CXX=clang++-3.8
        - CXXSTD=-std=c++1z

    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.9']
      env:
        - CXX=clang++-3.9
        - CXXSTD=-std=c++11

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-3.9', 'g++-4.9']
      env:
        - CXX=clang++-3.9
        - CXXSTD=-std=c++14

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-3.9', 'g++-4.9']
      env:
        - CXX=clang++-3.9
        - CXXSTD=-std=c++1z

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - CXX=clang++-4.0
        - CXXSTD=-std=c++11

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - CXX=clang++-4.0
        - CXXSTD=-std=c++14

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - CXX=clang++-4.0
        - CXXSTD=-std=c++1z

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0']
      env:
        - CXX=clang++-5.0
        - CXXSTD=-std=c++11

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0']
      env:
        - CXX=clang++-5.0
        - CXXSTD=-std=c++14

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'g++-7']
      env:
        - CXX=clang++-5.0
        - CXXSTD=-std=c++17

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0']
      env:
        - CXX=clang++-6.0
        - CXXSTD=-std=c++11

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0']
      env:
        - CXX=clang++-6.0
        - CXXSTD=-std=c++14

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0', 'g++-7']
      env:
        - CXX=clang++-6.0
        - CXXSTD=-std=c++17

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - CXX=clang++
        - CXXSTD=-std=c++11

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - CXX=clang++
        - CXXSTD=-std=c++14

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - CXX=clang++
        - CXXSTD=-std=c++1z

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - CXX=clang++
        - CXXSTD=-std=c++11

#    - os: osx
#      osx_image: xcode7.3
#      compiler: clang
#      env:
#        - CXX=clang++
#        - CXXSTD=-std=c++14

#    - os: osx
#      osx_image: xcode7.3
#      compiler: clang
#      env:
#        - CXX=clang++
#        - CXXSTD=-std=c++1z

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - CXX=clang++
        - CXXSTD=-std=c++11

#    - os: osx
#      osx_image: xcode8.3
#      compiler: clang
#      env:
#        - CXX=clang++
#        - CXXSTD=-std=c++14

#    - os: osx
#      osx_image: xcode8.3
#      compiler: clang
#      env:
#        - CXX=clang++
#        - CXXSTD=-std=c++1z

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env:
        - CXX=clang++
        - CXXSTD=-std=c++11

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env:
        - CXX=clang++
        - CXXSTD=-std=c++14

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env:
        - CXX=clang++
        - CXXSTD=-std=c++17

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CXXFLAGS="-O0 --coverage"
      before_script:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls --gcov gcov-7 --gcov-options '\-lp' --exclude src

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - CXX=g++-6
      script:
        - $CXX --version
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
        - cmake --build . --target test

script:
  - $CXX --version
  - make -j3 build/src/test/seq/tester
  - build/src/test/seq/tester
  - make -kj3
